export default {
	// * 已弃用
	// spaceOverview: '空间概览',
	// serviceCatalog: '服务目录',
	// instanceList: '服务列表',
	// detail: '服务详情',
	// outboundRoute: '对外路由',
	// basicResource: '基础资源',

	mysqlCreate: 'Mysql创建',
	redisCreate: 'Redis创建',
	elasticsearchCreate: 'Elasticsearch创建',
	rocketmqCreate: 'RocketMQ创建',
	dynamicForm: '发布服务',
	dataOverview: '数据总览',
	middlewareRepository: '中间件仓库',
	serviceList: '服务列表',
	serviceAvailable: '服务暴露',
	monitorAlarm: '监控告警',
	dataMonitor: '数据监控',
	logDetail: '日志详情',
	alarmCenter: '告警中心',
	disasterBackup: '容灾备份',
	disasterCenter: '灾备中心',
	dataSecurity: '数据安全',
	systemManagement: '系统管理',
	userManagement: '用户管理',
	roleManagement: '角色管理',
	operationAudit: '操作审计',
	resourcePoolManagement: '资源池管理',
	versionManagement: '版本管理',
	basicInfo: '基本详情',
	highAvailability: '实例详情',
	paramterSetting: '参数设置'
};
