export default {
	// * 已弃用
	// spaceOverview: '空间概览',
	// serviceCatalog: '服务目录',
	// instanceList: '服务列表',
	// detail: '服务详情',
	// outboundRoute: '对外路由',
	// basicResource: '基础资源',

	mysqlCreate: 'Mysql创建',
	redisCreate: 'Redis创建',
	elasticsearchCreate: 'Elasticsearch创建',
	rocketmqCreate: 'RocketMQ创建',
	dynamicForm: '发布服务',
	dataOverview: '数据总览',
	middlewareRepository: '中间件市场',
	serviceList: '服务列表',
	serverVersion: '服务版本',
	serviceAvailable: '服务暴露',
	monitorAlarm: '监控告警',
	dataMonitor: '数据监控',
	logDetail: '日志详情',
	alarmCenter: '服务告警',
	disasterBackup: '容灾备份',
	disasterCenter: '灾备中心',
	dataSecurity: '数据安全',
	systemManagement: '系统管理',
	systemAlarm: '系统告警',
	userManagement: '用户管理',
	roleManagement: '角色管理',
	operationAudit: '操作审计',
	resourcePoolManagement: '资源池',
	versionManagement: '版本管理',
	basicInfo: '服务详情',
	highAvailability: '服务详情',
	paramterSetting: '参数设置',
	addResourcePool: '添加资源池',
	addOther: '添加其他资源池',
	editResourcePool: '编辑资源池',
	editOther: '编辑其他资源池',
	resourcePoolDetail: '资源池详情'
};
